version: '3.9'

services:
  db:
    image: postgres:14
    container_name: luminalogix-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: luminalogix
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  server:
    build: ./apps/server
    container_name: luminalogix-backend
    environment:
      PORT: 5000
      DATABASE_URL: postgres://postgres:postgres@db:5432/luminalogix
      JWT_SECRET: super-secret-key
    depends_on:
      - db
    ports:
      - "5000:5000"

  client:
    build: ./apps/client
    container_name: luminalogix-frontend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:5000
    depends_on:
      - server
    ports:
      - "3000:3000"

volumes:
  db_data:
